language: swift
os: osx
osx_image: xcode8.3
before_install:
script:
  - xcodebuild clean -scheme ModelCache | xcpretty
  - xcodebuild -project ModelCache.xcodeproj -scheme ModelCache -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
  
